apiVersion: v1
kind: Service
metadata:
  name: global-load-balancer
  namespace: ingress-nginx
spec:
  selector:
    app: ingress-nginx-controller
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP