apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages-queue
  template:
    metadata:
      labels:
        app: messages-queue
    spec:
      containers:
        - name: messages-queue
          image: kamil20/messages-queue:latest
          imagePullPolicy: Always
          ports:
            - name: dashboard
              containerPort: 15672

            - name: connect
              containerPort: 5672

            - name: stomp
              containerPort: 61613
---
apiVersion: v1
kind: Service
metadata:
  name: messages-queue-service
spec:
  selector:
    app: messages-queue
  ports:
    - name: dashboard
      port: 15672
      targetPort: 15672

    - name: connect
      port: 5672
      targetPort: 5672

    - name: stomp
      port: 61613
      targetPort: 61613