apiVersion: v1
kind: Service
metadata:
  name: instagram-frontend
  labels:
    app: instagram-frontend
spec:
  selector:
    app: instagram-frontend
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP