apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-receiver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-backend-receiver
  template:
    metadata:
      labels:
        app: chat-backend-receiver
    spec:
      containers:
        - name: chat-backend-receiver
          image: kamil20/chat-backend-receiver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend-receiver-service
spec:
  selector:
    app: chat-backend-receiver
  ports:
    - port: 9300
      targetPort: 9300
