apiVersion: v1
kind: PersistentVolume
metadata:
  name: instagram-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/instagram/database/data"