apiVersion: v1
kind: Service
metadata:
  name: instagram-db
  labels:
    app: instagram-db
spec:
  selector:
    app: instagram-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP